# Generated by Django 5.1.4 on 2025-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('orderName', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
            ],
        ),
    ]
